package net.minecraft.src;
//Exported java file
//Keep in mind that you still need to fill in some blanks
// - ZeuX

public class Custom_Zombie extends ModelBase
{
	public Custom_Zombie()
	{
		LeftFoot = new ModelRenderer(this, 0, 0);
		LeftFoot.addBox(0F, 0F, 0F, 4, 12, 4, 0F);
		LeftFoot.setRotationPoint(0F, 12F, -2F);
		LeftFoot.rotateAngleX = 0F;
		LeftFoot.rotateAngleY = 0F;
		LeftFoot.rotateAngleZ = 0F;
		LeftFoot.mirror = false;
		RightFoot = new ModelRenderer(this, 0, 0);
		RightFoot.addBox(0F, 0F, 0F, 4, 12, 4, 0F);
		RightFoot.setRotationPoint(-4F, 12F, -2F);
		RightFoot.rotateAngleX = 0F;
		RightFoot.rotateAngleY = 0F;
		RightFoot.rotateAngleZ = 0F;
		RightFoot.mirror = false;
		Body1 = new ModelRenderer(this, 16, 11);
		Body1.addBox(0F, 0F, 0F, 8, 1, 4, 0F);
		Body1.setRotationPoint(-4F, 11F, -2F);
		Body1.rotateAngleX = 0F;
		Body1.rotateAngleY = 0F;
		Body1.rotateAngleZ = 0F;
		Body1.mirror = false;
		Body2 = new ModelRenderer(this, 16, 10);
		Body2.addBox(0F, 0F, 0F, 7, 1, 4, 0F);
		Body2.setRotationPoint(-3F, 10F, -2F);
		Body2.rotateAngleX = 0F;
		Body2.rotateAngleY = 0F;
		Body2.rotateAngleZ = 0F;
		Body2.mirror = false;
		Body3 = new ModelRenderer(this, 16, 9);
		Body3.addBox(0F, 0F, 0F, 7, 1, 4, 0F);
		Body3.setRotationPoint(-3F, 9F, -2F);
		Body3.rotateAngleX = 0F;
		Body3.rotateAngleY = 0F;
		Body3.rotateAngleZ = 0F;
		Body3.mirror = false;
		Body4 = new ModelRenderer(this, 16, 8);
		Body4.addBox(0F, 0F, 0F, 8, 1, 4, 0F);
		Body4.setRotationPoint(-4F, 8F, -2F);
		Body4.rotateAngleX = 0F;
		Body4.rotateAngleY = 0F;
		Body4.rotateAngleZ = 0F;
		Body4.mirror = false;
		Body5 = new ModelRenderer(this, 16, 7);
		Body5.addBox(0F, 0F, 0F, 7, 1, 4, 0F);
		Body5.setRotationPoint(-4F, 7F, -2F);
		Body5.rotateAngleX = 0F;
		Body5.rotateAngleY = 0F;
		Body5.rotateAngleZ = 0F;
		Body5.mirror = false;
		Body6 = new ModelRenderer(this, 16, 6);
		Body6.addBox(0F, 0F, 0F, 6, 1, 4, 0F);
		Body6.setRotationPoint(-4F, 6F, -2F);
		Body6.rotateAngleX = 0F;
		Body6.rotateAngleY = 0F;
		Body6.rotateAngleZ = 0F;
		Body6.mirror = false;
		Body7 = new ModelRenderer(this, 16, 5);
		Body7.addBox(0F, 0F, 0F, 5, 1, 4, 0F);
		Body7.setRotationPoint(-3F, 5F, -2F);
		Body7.rotateAngleX = 0F;
		Body7.rotateAngleY = 0F;
		Body7.rotateAngleZ = 0F;
		Body7.mirror = false;
		Body8 = new ModelRenderer(this, 16, 4);
		Body8.addBox(0F, 0F, 0F, 6, 1, 4, 0F);
		Body8.setRotationPoint(-3F, 4F, -2F);
		Body8.rotateAngleX = 0F;
		Body8.rotateAngleY = 0F;
		Body8.rotateAngleZ = 0F;
		Body8.mirror = false;
		Body9 = new ModelRenderer(this, 16, 3);
		Body9.addBox(0F, 0F, 0F, 8, 1, 4, 0F);
		Body9.setRotationPoint(-4F, 3F, -2F);
		Body9.rotateAngleX = 0F;
		Body9.rotateAngleY = 0F;
		Body9.rotateAngleZ = 0F;
		Body9.mirror = false;
		Body10 = new ModelRenderer(this, 16, 2);
		Body10.addBox(0F, 0F, 0F, 8, 1, 4, 0F);
		Body10.setRotationPoint(-4F, 2F, -2F);
		Body10.rotateAngleX = 0F;
		Body10.rotateAngleY = 0F;
		Body10.rotateAngleZ = 0F;
		Body10.mirror = false;
		Body11 = new ModelRenderer(this, 16, 1);
		Body11.addBox(0F, 0F, 0F, 8, 1, 4, 0F);
		Body11.setRotationPoint(-4F, 1F, -2F);
		Body11.rotateAngleX = 0F;
		Body11.rotateAngleY = 0F;
		Body11.rotateAngleZ = 0F;
		Body11.mirror = false;
		Body12 = new ModelRenderer(this, 16, 0);
		Body12.addBox(0F, 0F, 0F, 7, 1, 4, 0F);
		Body12.setRotationPoint(-3F, 0F, -2F);
		Body12.rotateAngleX = 0F;
		Body12.rotateAngleY = 0F;
		Body12.rotateAngleZ = 0F;
		Body12.mirror = false;
		LeftArm = new ModelRenderer(this, 0, 16);
		LeftArm.addBox(0F, 0F, 0F, 4, 10, 4, 0F);
		LeftArm.setRotationPoint(-8F, 0F, -2F);
		LeftArm.rotateAngleX = 0F;
		LeftArm.rotateAngleY = 0F;
		LeftArm.rotateAngleZ = 0F;
		LeftArm.mirror = false;
		RightArm = new ModelRenderer(this, 0, 16);
		RightArm.addBox(0F, 0F, 0F, 4, 10, 4, 0F);
		RightArm.setRotationPoint(4F, 0F, -2F);
		RightArm.rotateAngleX = 0F;
		RightArm.rotateAngleY = 0F;
		RightArm.rotateAngleZ = 0F;
		RightArm.mirror = false;
		RightHand = new ModelRenderer(this, 16, 16);
		RightHand.addBox(0F, 0F, 0F, 1, 1, 4, 0F);
		RightHand.setRotationPoint(7F, 10F, -2F);
		RightHand.rotateAngleX = 0F;
		RightHand.rotateAngleY = 0F;
		RightHand.rotateAngleZ = 0F;
		RightHand.mirror = false;
		RightFingers = new ModelRenderer(this, 16, 21);
		RightFingers.addBox(0F, 0F, 0F, 2, 1, 4, 0F);
		RightFingers.setRotationPoint(6F, 11F, -2F);
		RightFingers.rotateAngleX = 0F;
		RightFingers.rotateAngleY = 0F;
		RightFingers.rotateAngleZ = 0F;
		RightFingers.mirror = false;
		RightThumb = new ModelRenderer(this, 16, 26);
		RightThumb.addBox(0F, 0F, 0F, 1, 2, 1, 0F);
		RightThumb.setRotationPoint(4F, 10F, -2F);
		RightThumb.rotateAngleX = 0F;
		RightThumb.rotateAngleY = 0F;
		RightThumb.rotateAngleZ = 0F;
		RightThumb.mirror = false;
		LeftHand = new ModelRenderer(this, 16, 16);
		LeftHand.addBox(0F, 0F, 0F, 1, 1, 4, 0F);
		LeftHand.setRotationPoint(-8F, 10F, -2F);
		LeftHand.rotateAngleX = 0F;
		LeftHand.rotateAngleY = 0F;
		LeftHand.rotateAngleZ = 0F;
		LeftHand.mirror = false;
		LeftFingers = new ModelRenderer(this, 16, 21);
		LeftFingers.addBox(0F, 0F, 0F, 2, 1, 4, 0F);
		LeftFingers.setRotationPoint(-8F, 11F, -2F);
		LeftFingers.rotateAngleX = 0F;
		LeftFingers.rotateAngleY = 0F;
		LeftFingers.rotateAngleZ = 0F;
		LeftFingers.mirror = false;
		LeftThumb = new ModelRenderer(this, 16, 26);
		LeftThumb.addBox(0F, 0F, 0F, 1, 2, 1, 0F);
		LeftThumb.setRotationPoint(-5F, 10F, -2F);
		LeftThumb.rotateAngleX = 0F;
		LeftThumb.rotateAngleY = 0F;
		LeftThumb.rotateAngleZ = 0F;
		LeftThumb.mirror = false;
		Head = new ModelRenderer(this, 28, 16);
		Head.addBox(0F, 0F, 0F, 8, 8, 8, 0F);
		Head.setRotationPoint(-4F, -8F, -4F);
		Head.rotateAngleX = 0F;
		Head.rotateAngleY = 0F;
		Head.rotateAngleZ = 0F;
		Head.mirror = false;
	}
	
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5);
		LeftFoot.render(f5);
		RightFoot.render(f5);
		Body1.render(f5);
		Body2.render(f5);
		Body3.render(f5);
		Body4.render(f5);
		Body5.render(f5);
		Body6.render(f5);
		Body7.render(f5);
		Body8.render(f5);
		Body9.render(f5);
		Body10.render(f5);
		Body11.render(f5);
		Body12.render(f5);
		LeftArm.render(f5);
		RightArm.render(f5);
		RightHand.render(f5);
		RightFingers.render(f5);
		RightThumb.render(f5);
		LeftHand.render(f5);
		LeftFingers.render(f5);
		LeftThumb.render(f5);
		Head.render(f5);
	}
	
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5);
	}
	
	//fields
	public ModelRenderer LeftFoot;
	public ModelRenderer RightFoot;
	public ModelRenderer Body1;
	public ModelRenderer Body2;
	public ModelRenderer Body3;
	public ModelRenderer Body4;
	public ModelRenderer Body5;
	public ModelRenderer Body6;
	public ModelRenderer Body7;
	public ModelRenderer Body8;
	public ModelRenderer Body9;
	public ModelRenderer Body10;
	public ModelRenderer Body11;
	public ModelRenderer Body12;
	public ModelRenderer LeftArm;
	public ModelRenderer RightArm;
	public ModelRenderer RightHand;
	public ModelRenderer RightFingers;
	public ModelRenderer RightThumb;
	public ModelRenderer LeftHand;
	public ModelRenderer LeftFingers;
	public ModelRenderer LeftThumb;
	public ModelRenderer Head;
}
