// Date: 3/29/2013 6:42:04 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelZombie extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body1;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer body2;
    ModelRenderer body3;
    ModelRenderer body4;
    ModelRenderer body5;
    ModelRenderer body6;
    ModelRenderer body7;
    ModelRenderer body8;
    ModelRenderer body9;
    ModelRenderer body10;
    ModelRenderer body11;
    ModelRenderer body12;
    ModelRenderer Shape1;
    ModelRenderer Shape3;
    ModelRenderer Shape2;
    ModelRenderer Shape4;
  
  public ModelZombie()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, 0F, 0F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body1 = new ModelRenderer(this, 17, 16);
      body1.addBox(-4F, 0F, -2F, 7, 1, 4);
      body1.setRotationPoint(0F, 11F, 0F);
      body1.setTextureSize(64, 32);
      body1.mirror = true;
      setRotation(body1, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 48, 15);
      rightarm.addBox(-3F, -1F, -2F, 4, 10, 4);
      rightarm.setRotationPoint(-5F, 2F, 0F);
      rightarm.setTextureSize(64, 32);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0F);
      leftarm = new ModelRenderer(this, 48, 0);
      leftarm.addBox(-1F, -2F, -2F, 4, 11, 4);
      leftarm.setRotationPoint(5F, 2F, 0F);
      leftarm.setTextureSize(64, 32);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, 0F);
      rightleg = new ModelRenderer(this, 0, 16);
      rightleg.addBox(-1F, 0F, -2F, 4, 12, 4);
      rightleg.setRotationPoint(-3F, 12F, 0F);
      rightleg.setTextureSize(64, 32);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      leftleg.mirror = true;
      leftleg = new ModelRenderer(this, 0, 16);
      leftleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      leftleg.setRotationPoint(2F, 12F, 0F);
      leftleg.setTextureSize(64, 32);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      leftleg.mirror = false;
      body2 = new ModelRenderer(this, 17, 17);
      body2.addBox(-4F, 0F, -2F, 7, 1, 4);
      body2.setRotationPoint(0F, 10F, 0F);
      body2.setTextureSize(64, 32);
      body2.mirror = true;
      setRotation(body2, 0F, 0F, 0F);
      body3 = new ModelRenderer(this, 18, 18);
      body3.addBox(-2F, 0F, -2F, 6, 1, 4);
      body3.setRotationPoint(0F, 9F, 0F);
      body3.setTextureSize(64, 32);
      body3.mirror = true;
      setRotation(body3, 0F, 0F, 0F);
      body4 = new ModelRenderer(this, 17, 19);
      body4.addBox(-3F, 0F, -2F, 7, 1, 4);
      body4.setRotationPoint(0F, 8F, 0F);
      body4.setTextureSize(64, 32);
      body4.mirror = true;
      setRotation(body4, 0F, 0F, 0F);
      body5 = new ModelRenderer(this, 18, 20);
      body5.addBox(-3F, 0F, -2F, 6, 1, 4);
      body5.setRotationPoint(0F, 7F, 0F);
      body5.setTextureSize(64, 32);
      body5.mirror = true;
      setRotation(body5, 0F, 0F, 0F);
      body6 = new ModelRenderer(this, 18, 21);
      body6.addBox(-4F, 0F, -2F, 6, 1, 4);
      body6.setRotationPoint(0F, 6F, 0F);
      body6.setTextureSize(64, 32);
      body6.mirror = true;
      setRotation(body6, 0F, 0F, 0F);
      body7 = new ModelRenderer(this, 18, 22);
      body7.addBox(-4F, 0F, -2F, 6, 1, 4);
      body7.setRotationPoint(0F, 5F, 0F);
      body7.setTextureSize(64, 32);
      body7.mirror = true;
      setRotation(body7, 0F, 0F, 0F);
      body8 = new ModelRenderer(this, 18, 23);
      body8.addBox(-3F, 0F, -2F, 6, 1, 4);
      body8.setRotationPoint(0F, 4F, 0F);
      body8.setTextureSize(64, 32);
      body8.mirror = true;
      setRotation(body8, 0F, 0F, 0F);
      body9 = new ModelRenderer(this, 17, 24);
      body9.addBox(-3F, 0F, -2F, 7, 1, 4);
      body9.setRotationPoint(0F, 3F, 0F);
      body9.setTextureSize(64, 32);
      body9.mirror = true;
      setRotation(body9, 0F, 0F, 0F);
      body10 = new ModelRenderer(this, 16, 25);
      body10.addBox(-4F, 0F, -2F, 8, 1, 4);
      body10.setRotationPoint(0F, 2F, 0F);
      body10.setTextureSize(64, 32);
      body10.mirror = true;
      setRotation(body10, 0F, 0F, 0F);
      body11 = new ModelRenderer(this, 16, 26);
      body11.addBox(-4F, 0F, -2F, 8, 1, 4);
      body11.setRotationPoint(0F, 1F, 0F);
      body11.setTextureSize(64, 32);
      body11.mirror = true;
      setRotation(body11, 0F, 0F, 0F);
      body12 = new ModelRenderer(this, 17, 27);
      body12.addBox(-3F, 0F, -2F, 7, 1, 4);
      body12.setRotationPoint(0F, 0F, 0F);
      body12.setTextureSize(64, 32);
      body12.mirror = true;
      setRotation(body12, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 32, 0);
      Shape1.addBox(0F, 0F, -1F, 1, 1, 1);
      Shape1.setRotationPoint(-5F, 11F, -1F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 32, 2);
      Shape3.addBox(-1F, 0F, -2F, 1, 2, 4);
      Shape3.setRotationPoint(-7F, 11F, 0F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 32, 2);
      Shape2.addBox(0F, 0F, -2F, 1, 2, 4);
      Shape2.setRotationPoint(7F, 11F, 0F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 32, 0);
      Shape4.addBox(-1F, 0F, -1F, 1, 1, 1);
      Shape4.setRotationPoint(5F, 11F, -1F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    head.render(f5);
    body1.render(f5);
    rightarm.render(f5);
    leftarm.render(f5);
    rightleg.render(f5);
    leftleg.render(f5);
    body2.render(f5);
    body3.render(f5);
    body4.render(f5);
    body5.render(f5);
    body6.render(f5);
    body7.render(f5);
    body8.render(f5);
    body9.render(f5);
    body10.render(f5);
    body11.render(f5);
    body12.render(f5);
    Shape1.render(f5);
    Shape3.render(f5);
    Shape2.render(f5);
    Shape4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
